### ISSUE TITLE
Architecture Review

### ISSUE THREAD

**Issue by JohanCSmit** [COS301-SE-2022/Exploring-Self-Sovereign-Identity#98]
Please review the following document:
https://docs.google.com/document/d/1K8oaeW0VkI6FaNpQitD8Rwj0JDO7pfM9/edit?usp=sharing&ouid=107214848388233428436&rtpof=true&sd=true

**Comment by RebeccaPillay** [comment]
Looks perfect. Aligns with the definition of Architectural Styles and Patterns, as I understand it. Happy with the updated quality requirements too.
